# Generated by Django 5.2.15 on 2026-06-23 21:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0002_alter_parcel_created_at'),
        ('riders', '0002_alter_deliveryman_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('assignment', 'Assignment'), ('reassignment', 'Reassignment')], default='assignment', max_length=14)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=255)),
                ('tracking_id', models.CharField(blank=True, max_length=30)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='parcels.parcel')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='riders.deliveryman')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
