# Generated by Django 5.2.15 on 2026-06-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('districts', models.JSONField(blank=True, default=list)),
                ('regular_charge', models.IntegerField(default=0)),
                ('express_charge', models.IntegerField(default=0)),
                ('cod_charge_percent', models.FloatField(default=1.0)),
                ('return_charge', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
