# Generated by Django 5.2.15 on 2026-06-23 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('merchants', '0001_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=30, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('alternative_phone', models.CharField(blank=True, max_length=30)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=80)),
                ('upazila', models.CharField(blank=True, max_length=80)),
                ('zone', models.CharField(blank=True, max_length=80)),
                ('delivery_type', models.CharField(choices=[('regular', 'Regular'), ('express', 'Express')], default='regular', max_length=10)),
                ('delivery_method', models.CharField(choices=[('home', 'Home'), ('point', 'Point')], default='home', max_length=10)),
                ('weight', models.FloatField(default=0.5)),
                ('product_description', models.CharField(blank=True, max_length=255)),
                ('special_instructions', models.CharField(blank=True, max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=60)),
                ('is_exchange', models.BooleanField(default=False)),
                ('cod_amount', models.IntegerField(default=0)),
                ('collected_cod', models.IntegerField(blank=True, null=True)),
                ('delivery_charge', models.IntegerField(default=0)),
                ('cod_charge', models.IntegerField(default=0)),
                ('total_charge', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('return_in_transit', 'Return in Transit'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_otp', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('current_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='branches.branch')),
                ('delivery_man', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='riders.deliveryman')),
                ('destination_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='branches.branch')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='merchants.merchant')),
                ('origin_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='branches.branch')),
                ('owner_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_parcels', to='branches.branch')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParcelStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('return_in_transit', 'Return in Transit'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], max_length=20)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.CharField(blank=True, max_length=120)),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='proof/')),
                ('proof_note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parcels.parcel')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
    ]
