# Generated by Django 5.2.15 on 2026-07-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_alter_parcel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivery_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('express', 'Express')], default='express', max_length=10),
        ),
    ]
