# Generated by Django 5.2.15 on 2026-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_alter_parcel_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('at_hub', 'At Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('return_in_transit', 'Return in Transit'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcelstatusevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('at_hub', 'At Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('return_in_transit', 'Return in Transit'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
