# Generated by Django 5.2.15 on 2026-07-06 10:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('parcels', '0004_alter_parcel_status_alter_parcelstatusevent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('dispatched', 'Dispatched'), ('received', 'Received')], default='open', max_length=12)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('from_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_bags', to='branches.branch')),
                ('parcels', models.ManyToManyField(blank=True, related_name='bags', to='parcels.parcel')),
                ('to_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_bags', to='branches.branch')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
