# Generated by Django 5.2.15 on 2026-07-06 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('parcels', '0005_bag'),
        ('riders', '0002_alter_deliveryman_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='reattempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('closed', 'Closed')], default='in_progress', max_length=12)),
                ('expected_cod', models.IntegerField(default=0)),
                ('due_cod', models.IntegerField(default=0)),
                ('collected_cod', models.IntegerField(default=0)),
                ('cod_reconciled', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='branches.branch')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='riders.deliveryman')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TripParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], max_length=10)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('partial', 'Partially Delivered'), ('failed', 'Failed'), ('picked_up', 'Picked Up')], default='pending', max_length=12)),
                ('cod_amount', models.IntegerField(default=0)),
                ('collected_cod', models.IntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, max_length=150)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_items', to='parcels.parcel')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parcels.trip')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('trip', 'parcel')},
            },
        ),
    ]
