# Generated by Django 5.2.15 on 2026-07-06 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('parcels', '0006_parcel_reattempt_count_trip_tripparcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='returning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcelstatusevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('pickup', 'Pickup'), ('hub_inbound', 'Hub Inbound'), ('hub_outbound', 'Hub Outbound'), ('sort', 'Sorted'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('return', 'Return'), ('note', 'Note')], max_length=20),
        ),
        migrations.AddField(
            model_name='parcelstatusevent',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='branches.branch'),
        ),
    ]
