# Generated by Django 5.2.15 on 2026-06-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('central', 'Central'), ('hub', 'Hub')], default='hub', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(max_length=80)),
                ('thana', models.CharField(blank=True, max_length=80)),
                ('coverage_thanas', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
