# Generated by Django 5.2.15 on 2026-06-23 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0002_alter_merchant_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('bank', 'Bank'), ('mobile', 'Mobile')], default='mobile', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('min_amount', models.IntegerField(default=0)),
                ('charge_percent', models.FloatField(default=0)),
                ('instructions', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MerchantPayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('bank', 'Bank'), ('mobile', 'Mobile')], max_length=10)),
                ('account_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=60)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to='merchants.merchant')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.availablepaymentmethod')),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('charge', models.IntegerField(default=0)),
                ('payout_label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('requested_at', models.DateField(default=django.utils.timezone.localdate)),
                ('processed_at', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='merchants.merchant')),
                ('payout_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.merchantpayoutmethod')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
    ]
