# Generated by Django 5.2.15 on 2026-06-23 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0002_alter_merchant_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('parcel', 'Parcel'), ('payment', 'Payment'), ('pickup', 'Pickup'), ('account', 'Account'), ('other', 'Other')], default='other', max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=12)),
                ('tracking_id', models.CharField(blank=True, max_length=30)),
                ('unread_for_admin', models.BooleanField(default=True)),
                ('unread_for_merchant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('merchant', 'Merchant'), ('admin', 'Admin')], max_length=10)),
                ('sender_name', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='support/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
