# Generated by Django 5.2.15 on 2026-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_alter_deliveryman_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
