# Generated by Django 5.2.15 on 2026-06-23 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('riders', '0002_alter_deliveryman_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('parcel_count', models.IntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='pending', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('remitted_at', models.DateField(default=django.utils.timezone.localdate)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='branches.branch')),
            ],
            options={
                'ordering': ['-remitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RiderHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=150)),
                ('amount', models.IntegerField(default=0)),
                ('parcel_count', models.IntegerField(default=0)),
                ('parcel_ids', models.JSONField(blank=True, default=list)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='pending', max_length=12)),
                ('remitted_at', models.DateField(default=django.utils.timezone.localdate)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('confirmed_by', models.CharField(blank=True, max_length=120)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_handovers', to='branches.branch')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='riders.deliveryman')),
            ],
            options={
                'ordering': ['-remitted_at', '-id'],
            },
        ),
    ]
