# Generated by Django 5.2.15 on 2026-07-05 09:53

import apps.merchants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_merchantwebhook_webhookdelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantapikey',
            name='key_hash',
        ),
        migrations.RemoveField(
            model_name='merchantapikey',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='merchantwebhook',
            name='secret',
        ),
        migrations.AddField(
            model_name='merchantapikey',
            name='api_key',
            field=models.CharField(db_index=True, default=apps.merchants.models.generate_api_key, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='merchantapikey',
            name='secret_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='merchantwebhook',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='merchantwebhook',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
